name: Build NaiveProxy Docker Images

on:

  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/**'
      - 'BuildEnv/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/**'
      - 'BuildEnv/**'

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cunoe/naiveproxy
          tags: "server"
          target: server-prod

  build-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cunoe/naiveproxy
          tags: "client"
          target: client-prod
